server:
  port: 8080

spring:
  application:
    name: post-ms
  datasource:
    url: jdbc:mysql://localhost:3306/post
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
  profiles:
    active: prod
logging:
  level:
    com.ballnet.postservice: debug
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
    org.hibernate.type.descriptor.sql: trace
management:
  endpoints:
    web:
      exposure:
        include=*:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    path: /swagger-ui.html
kafka:
  bootstrapAddress: http://localhost:9092
  topic:
    notification:
      partition: 8
      replication: 1